name: IT tests
on:
  push:
    branches:
      - main
jobs:
  it-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: trino
      - name: Deploy trino
        run: kubectl apply -f tests/it/trino.yml
      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=ready pods -n trino-system --all --timeout=120s
      - name: Test
        run: |
          kubectl -n trino-system port-forward svc/trino 8080:8080 > /dev/null &
          sleep 10 # give it a little bit more time to start
          yarn test:it --testTimeout=60000
